[versions]
minSdk = "26"
targetSdk = "34"
compileSdk = "34"
versionCode = "1"
versionName = "1.0.0"
agp = "8.2.2"
kotlin = "1.9.22"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.9.0"
composeBom = "2024.05.00"
appcompat = "1.6.1"
material = "1.11.0"
androidGradlePlugin = "8.2.2"
androidTools = "31.4.0"
kotlinter = "4.2.0"
ksp = "1.9.22-1.0.18"
room = "2.6.1"
androidxComposeCompiler = "1.5.7"
androidxLifecycle = "2.7.0"
androidxNavigation = "2.7.7"
hilt = "2.50"
hiltExt = "1.2.0"
jacoco = "0.8.7"
androidxHiltNavigationCompose = "1.2.0"
firebaseCrashlyticsBuildtools = "2.9.9"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
ktlint-kotlinter = { group = "org.jmailen.gradle", name = "kotlinter-gradle", version.ref = "kotlinter" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }

[bundles]
compose = [
    "androidx-compose-ui",
    "androidx-compose-graphics",
    "androidx-compose-preview",
    "androidx-compose-material3",
    "androidx-compose-material-iconsExtended"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
android-room = { id = "androidx.room", version.ref = "room" }

# Plugins defined by this project
weather-android-application = { id = "weather.android.application", version = "unspecified" }
weather-android-application-compose = { id = "weather.android.application.compose", version = "unspecified" }
weather-android-library = { id = "weather.android.library", version = "unspecified" }
weather-android-library-compose = { id = "weather.android.library.compose", version = "unspecified" }
weather-android-feature = { id = "weather.android.feature", version = "unspecified" }
weather-android-hilt = { id = "weather.android.hilt", version = "unspecified" }
weather-android-room = { id = "weather.android.room", version = "unspecified" }
weather-android-application-jacoco = { id = "weather.android.application.jacoco", version = "unspecified" }
weather-android-library-jacoco = { id = "weather.android.library.jacoco", version = "unspecified" }
androidTest = { id = "com.android.test", version.ref = "androidGradlePlugin" }
